# -*- coding: utf-8 -*-
"""Age of the Universe H0=70

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vKEtBhqPTIObHWugkSfHzgseUqA9qOPU
"""

import astropy.units as u # Importing astronomy units package
import astropy.constants as ac # Importing astronomy constants package (such as G=9.8 m/s**2)
import numpy as np

H0 = 70 # Hubble constant
Mpc_in_km = 3.086e22 # Megaparsec in kilometers
seconds_in_year = 3.154e7 # Seconds in a year

H0_per_s = H0 / Mpc_in_km # Calculating Hubble constant to 1/s
print (H0_per_s / u.s)

age_in_seconds = 1 / H0_per_s # Calculating age in seconds
print (age_in_seconds * u.s)

age_in_years = age_in_seconds / seconds_in_year # Calculating age in years
print (age_in_years * u.year)